on:
  issue_comment:
    types: [ created ]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        if: contains(github.event.comment.body, '/support')
        run: |
        echo say hello
        env:
          NUMBER: ${{ github.event.issue.number }}