name: Get Custom Field Value
on:
  push:
    branches:
        david/AP-5

jobs:
  getJiraKey:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract Jira Key from Branch Name
        run: |
          branchName=$(git symbolic-ref --short HEAD)
          if [[ $branchName =~ ([A-Z][A-Z0-9]+-[0-9]+) ]]; then
          jiraKey=${BASH_REMATCH[1]}
          echo "jiraKey=$jiraKey" >> $GITHUB_ENV
          fi
      - name: Get test scenarios
        if: ${{ env.jiraKey != '' }}
        run: |
          apiEndpoint=https://${{secrets.JIRA_DOMAIN}}/rest/api/2/issue/${{ env.jiraKey }}
          echo "testScenarios<<EOF" >> $GITHUB_ENV
          curl --request GET --url $apiEndpoint --user ${{secrets.JIRA_EMAIL}}:${{secrets.JIRA_TOKEN}} --header 'Accept: application/json' | jq -r '.fields.customfield_10038' | awk '/---Test scenarios/{flag=1; next} /---/{flag=0} flag' | grep -v 'checked' | sed 's/text: //g' >> $GITHUB_ENV           
          echo "EOF" >> $GITHUB_ENV
      - name: Leave a comment
        if: ${{ env.testScenarios != '' }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🧪 Test scenarios for this story 🧪 
            ${{ env.testScenarios }}
