on:
  pull_request:
    branches:
      - main
    types: [ opened, ready_for_review, synchronize ]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"Job Failed","text_description":"See job details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}
  visual-testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Recognize sha ref
        id: sharef
        run: |
          if [ "$EVENT" == 'pull_request' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.pull_request.head.sha}})"
          elif [ "$EVENT" == 'workflow_run' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.workflow_run.head_sha}})"
          else
            echo "::set-output name=sha::$(echo $GITHUB_SHA)"
          fi
        env:
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
            sha: ${{ steps.sharef.outputs.sha }}
            token: ${{ secrets.GITHUB_TOKEN }}
            name: visual-testing
            conclusion: "neutral"
            details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            output: |
              {"summary":"Job Failed","text_description":"See job details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}                    

      #      - name: Install dependencies
#        run: yarn install --frozen-lockfile
#      - name: Install Playwright
#        run: yarn playwright install --with-deps
#      - name: Download from s3
#        run: |
#          aws s3 sync s3://baseline-snapshots/playwright-snapshots/ snapshots/
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: 'eu-central-1'
#      - name: Run your tests
#        run: yarn test
#      - name: Upload test report to s3
#        if: failure()
#        run: |
#          aws s3 sync playwright-report s3://visual-playwright-reports/${{ github.head_ref }}
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: 'eu-central-1'
#      - name: Link report in comment
#        if: failure()
#        uses: peter-evans/create-or-update-comment@v2
#        with:
#          issue-number: ${{ github.event.number  }}
#          body: |
#            This PR introduces visual changes, please check them out here! [Visual tests report](https://visual-playwright-reports.s3.eu-central-1.amazonaws.com/${{ github.head_ref }}/index.html)
